import { writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const clientPkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8")) as {
  version: string;
};
const rootPkg = JSON.parse(readFileSync(join(here, "..", "..", "..", "package.json"), "utf8")) as {
  version: string;
};

const out = `// AUTO-GENERATED — do not edit. Regenerated by scripts/gen-version.ts before build.
export const CLIENT_VERSION = ${JSON.stringify(clientPkg.version)};
export const BUILT_FOR_API_VERSION = ${JSON.stringify(rootPkg.version)};
`;

writeFileSync(join(here, "..", "src", "version.ts"), out);
console.log(
  `[gen-version] CLIENT_VERSION=${clientPkg.version} BUILT_FOR_API_VERSION=${rootPkg.version}`,
);
